#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/api_core/ && \
    dotnet build src/api_core/ && \
    echo "Now, run the following to start the project: dotnet run -p src/api_core/api_core.csproj --launch-profile web"
