openapi: 3.0.0
info:
  title: Python to .Net
  description: Still whitout description.
  version: 0.25.1
servers:
- url: http://www.skycoin.net
  description: Main Skycoin server
- url: http://staging.node.skycoin.net
  description: Internal staging server for developer.
components:
  securitySchemes:
    CsrfTokenAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: X-CSRF-TOKEN  # name of the header, query parameter or cookie
  schemas:
    genericError:
      description: This is a generic error that should be default response
      type: object
      properties:
        code:
          type: integer
          format: int64
        message:
          type: string
    
    
      
paths:
  /api/transactions/single:           #issue 8
    post:
      summary: Build not signed single transaction
      description: Should build not signed transaction to transfer from the single source to the single destination. If the transaction with the specified operationId has already been built by one of the [POST] /api/transactions/* call, it should be ignored and regular response (as in the first request) should be returned.
      
      security:
      - CsrfTokenAuth: []

      requestBody:
        required: true
        description: Transaction object
        content:
          application/json:
            schema:
              description: Object representing the transaction
              type: object
              properties:
                operationId:
                  description: Operation ID
                  type: string
                fromAddress: 
                  type: string
                  description: Source address
                toAddress:
                  type: string
                  description: Destination address
                assetId:
                  type: string
                  description: Asset ID to transfer
                includeFee:
                  type: boolean
                  description: Ignored. No Fiber coin implements this ... yet
                amount: 
                  type: string
                  description: Amount to transfer. Integer as string, aligned to the asset accuracy. Actual value can be calculated as x = amount / (10 ^ asset.Accuracy)
                
             
              
                

      responses:
        '200':    # status code
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  
                  ErrorCode:
                    description: Error Code
                    type: string
                    enum:
                    - amountIsTooSmall
                    - notEnoughBalance
                  
                  transactionContext:
                    description: The transaction context which will be passed to the [POST] /api/sign
                    type: string
                  
        default:
          $ref : '#/components/schemas/genericError'
          
          
  /api/balances:      #issue 9
    get:
      summary: Return balance of the observed wallets
      description: Should return balances of the observed wallets with non zero balances. Wallets balance observation is enabled by the [POST] /api/balances/{address}/observation and disabled by the [DELETE] /api/balances/{address}/observation.
      parameters:
        - name: take
          in: query
          required: true
          schema:
            type: integer
          description: Limit amount of the returned values
        - name: continuation
          in: query
          required: false
          schema:
            type: string
          description: context of the previous request
          
      responses:
        '200':    # status code
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  isValid:
                    description: Indicate if the address is valid
                    type: boolean
                  
                  continuation:
                    description: Continuation token 
                    type: string
                  
                  items:
                    description: Current batch of items
                    type: array
                    items:
                      type: object
                      properties:
                        address:
                          description: Wallet address
                          type: string
                        assetId:
                          description: Asset ID
                          type: string
                       
                        balance:
                          description: Balance is integer as string, aligned to the asset accuracy. Actual value can be calculated as x = sourceBalance * (10 ^ asset.Accuracy)Balance is integer as string, aligned to the asset accuracy. Actual value can be calculated as x = sourceBalance * (10 ^ asset.Accuracy)
                          type: string
                        block:
                          description: Incremental ID of the moment, when balance is updated. It should be the same sequence as for block in the []GET] /api/transactions/broadcast/* responses
                          type: integer
                        
                        
                        
                  
        default:
          $ref : '#/components/schemas/genericError'
        
        
          

# To remember :
#  Every post method should use security schema.
#  Feel free to use and reuse components
#  I think, at some point, someone should use oneOf and anyOf, pls take a look
