/*
 * Python to .Net
 *
 * Still whitout description.
 *
 * OpenAPI spec version: 0.25.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace api_core.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class ApitransactionmanyinputsInputs : IEquatable<ApitransactionmanyinputsInputs>
    { 
        /// <summary>
        /// Source Address
        /// </summary>
        /// <value>Source Address</value>
        [DataMember(Name="fromAddress")]
        public string FromAddress { get; set; }

        /// <summary>
        /// Amount to transfer from the  fromAddress. Integer as string, aligned to the droplet precision exponent. Actual value can be calculated as x &#x3D; amount / (10 ^ asset.Accuracy).
        /// </summary>
        /// <value>Amount to transfer from the  fromAddress. Integer as string, aligned to the droplet precision exponent. Actual value can be calculated as x &#x3D; amount / (10 ^ asset.Accuracy).</value>
        [DataMember(Name="amount")]
        public string Amount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ApitransactionmanyinputsInputs {\n");
            sb.Append("  FromAddress: ").Append(FromAddress).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ApitransactionmanyinputsInputs)obj);
        }

        /// <summary>
        /// Returns true if ApitransactionmanyinputsInputs instances are equal
        /// </summary>
        /// <param name="other">Instance of ApitransactionmanyinputsInputs to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ApitransactionmanyinputsInputs other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    FromAddress == other.FromAddress ||
                    FromAddress != null &&
                    FromAddress.Equals(other.FromAddress)
                ) && 
                (
                    Amount == other.Amount ||
                    Amount != null &&
                    Amount.Equals(other.Amount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (FromAddress != null)
                    hashCode = hashCode * 59 + FromAddress.GetHashCode();
                    if (Amount != null)
                    hashCode = hashCode * 59 + Amount.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ApitransactionmanyinputsInputs left, ApitransactionmanyinputsInputs right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ApitransactionmanyinputsInputs left, ApitransactionmanyinputsInputs right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
