/*
 * Python to .Net
 *
 * Still whitout description.
 *
 * OpenAPI spec version: 0.25.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace api_core.Models
{ 
    /// <summary>
    /// ewr
    /// </summary>
    [DataContract]
    public partial class InlineObject1 : IEquatable<InlineObject1>
    { 
        /// <summary>
        /// Operation ID
        /// </summary>
        /// <value>Operation ID</value>
        [DataMember(Name="operationId")]
        public string OperationId { get; set; }

        /// <summary>
        /// Sources
        /// </summary>
        /// <value>Sources</value>
        [DataMember(Name="inputs")]
        public List<ApitransactionmanyinputsInputs> Inputs { get; set; }

        /// <summary>
        /// Destination Address
        /// </summary>
        /// <value>Destination Address</value>
        [DataMember(Name="toAddress")]
        public string ToAddress { get; set; }

        /// <summary>
        /// Ticker ID of the fiber coin, SKY by default
        /// </summary>
        /// <value>Ticker ID of the fiber coin, SKY by default</value>
        [DataMember(Name="assetId")]
        public string AssetId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineObject1 {\n");
            sb.Append("  OperationId: ").Append(OperationId).Append("\n");
            sb.Append("  Inputs: ").Append(Inputs).Append("\n");
            sb.Append("  ToAddress: ").Append(ToAddress).Append("\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineObject1)obj);
        }

        /// <summary>
        /// Returns true if InlineObject1 instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineObject1 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineObject1 other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    OperationId == other.OperationId ||
                    OperationId != null &&
                    OperationId.Equals(other.OperationId)
                ) && 
                (
                    Inputs == other.Inputs ||
                    Inputs != null &&
                    Inputs.SequenceEqual(other.Inputs)
                ) && 
                (
                    ToAddress == other.ToAddress ||
                    ToAddress != null &&
                    ToAddress.Equals(other.ToAddress)
                ) && 
                (
                    AssetId == other.AssetId ||
                    AssetId != null &&
                    AssetId.Equals(other.AssetId)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (OperationId != null)
                    hashCode = hashCode * 59 + OperationId.GetHashCode();
                    if (Inputs != null)
                    hashCode = hashCode * 59 + Inputs.GetHashCode();
                    if (ToAddress != null)
                    hashCode = hashCode * 59 + ToAddress.GetHashCode();
                    if (AssetId != null)
                    hashCode = hashCode * 59 + AssetId.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineObject1 left, InlineObject1 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineObject1 left, InlineObject1 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
