/*
 * Python to .Net
 *
 * Still whitout description.
 *
 * OpenAPI spec version: 0.25.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace api_core.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InlineResponse2003 : IEquatable<InlineResponse2003>
    { 
        /// <summary>
        /// Name of the service
        /// </summary>
        /// <value>Name of the service</value>
        [DataMember(Name="name")]
        public string Name { get; set; }

        /// <summary>
        /// Version of the service
        /// </summary>
        /// <value>Version of the service</value>
        [DataMember(Name="version")]
        public string Version { get; set; }

        /// <summary>
        /// ENV_INFO environment variable value
        /// </summary>
        /// <value>ENV_INFO environment variable value</value>
        [DataMember(Name="env")]
        public string Env { get; set; }

        /// <summary>
        /// Flag, wich indicates if the service is built in the debug configuration or not
        /// </summary>
        /// <value>Flag, wich indicates if the service is built in the debug configuration or not</value>
        [DataMember(Name="isDebug")]
        public bool? IsDebug { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineResponse2003 {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Version: ").Append(Version).Append("\n");
            sb.Append("  Env: ").Append(Env).Append("\n");
            sb.Append("  IsDebug: ").Append(IsDebug).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineResponse2003)obj);
        }

        /// <summary>
        /// Returns true if InlineResponse2003 instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineResponse2003 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineResponse2003 other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Name == other.Name ||
                    Name != null &&
                    Name.Equals(other.Name)
                ) && 
                (
                    Version == other.Version ||
                    Version != null &&
                    Version.Equals(other.Version)
                ) && 
                (
                    Env == other.Env ||
                    Env != null &&
                    Env.Equals(other.Env)
                ) && 
                (
                    IsDebug == other.IsDebug ||
                    IsDebug != null &&
                    IsDebug.Equals(other.IsDebug)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Name != null)
                    hashCode = hashCode * 59 + Name.GetHashCode();
                    if (Version != null)
                    hashCode = hashCode * 59 + Version.GetHashCode();
                    if (Env != null)
                    hashCode = hashCode * 59 + Env.GetHashCode();
                    if (IsDebug != null)
                    hashCode = hashCode * 59 + IsDebug.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineResponse2003 left, InlineResponse2003 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineResponse2003 left, InlineResponse2003 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
