/*
 * Python to .Net
 *
 * Still whitout description.
 *
 * OpenAPI spec version: 0.25.1
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace api_core.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class InlineObject4 : IEquatable<InlineObject4>
    { 
        /// <summary>
        /// Gets or Sets PrivateKeys
        /// </summary>
        [DataMember(Name="privateKeys")]
        public List<string> PrivateKeys { get; set; }

        /// <summary>
        /// Gets or Sets TransactionContext
        /// </summary>
        [DataMember(Name="transactionContext")]
        public string TransactionContext { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InlineObject4 {\n");
            sb.Append("  PrivateKeys: ").Append(PrivateKeys).Append("\n");
            sb.Append("  TransactionContext: ").Append(TransactionContext).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((InlineObject4)obj);
        }

        /// <summary>
        /// Returns true if InlineObject4 instances are equal
        /// </summary>
        /// <param name="other">Instance of InlineObject4 to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InlineObject4 other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    PrivateKeys == other.PrivateKeys ||
                    PrivateKeys != null &&
                    PrivateKeys.SequenceEqual(other.PrivateKeys)
                ) && 
                (
                    TransactionContext == other.TransactionContext ||
                    TransactionContext != null &&
                    TransactionContext.Equals(other.TransactionContext)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (PrivateKeys != null)
                    hashCode = hashCode * 59 + PrivateKeys.GetHashCode();
                    if (TransactionContext != null)
                    hashCode = hashCode * 59 + TransactionContext.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(InlineObject4 left, InlineObject4 right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(InlineObject4 left, InlineObject4 right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
